version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: watchdog
    versions:
    - 1.0.2
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: pytest
    versions:
    - 6.2.2
